from django import forms
from .models import *
from django.forms import DateInput, DateTimeInput, TimeInput, CheckboxInput, Textarea, TextInput


class LoanAgingLiveForm(forms.Form):
	overdue_0_30_days = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	overdue_31_60_days = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	overdue_61_90_days = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	overdue_91_days_plus = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	total_outstanding_loans = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	reported_date = forms.DateField(required=True, widget=forms.DateInput(attrs={"type": "date","class": "form-control"}))
	comments = forms.CharField( required=True, widget=forms.Textarea(attrs={"class": "form-control"}))
class LoanAgingTempForm(forms.Form):
	overdue_0_30_days = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	overdue_31_60_days = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	overdue_61_90_days = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	overdue_91_days_plus = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	total_outstanding_loans = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	reported_date = forms.DateField(required=True, widget=forms.DateInput(attrs={"type": "date","class": "form-control"}))
	comments = forms.CharField( required=True, widget=forms.Textarea(attrs={"class": "form-control"}))
class LoanAgingTempPAForm(forms.Form):
	overdue_0_30_days = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	overdue_31_60_days = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	overdue_61_90_days = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	overdue_91_days_plus = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	total_outstanding_loans = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	reported_date = forms.DateField(required=True, widget=forms.DateInput(attrs={"type": "date","class": "form-control"}))
	comments = forms.CharField( required=True, widget=forms.Textarea(attrs={"class": "form-control"}))
class LoanAgingTempUpdateForm(forms.Form):
	overdue_0_30_days = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	overdue_31_60_days = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	overdue_61_90_days = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	overdue_91_days_plus = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	total_outstanding_loans = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	reported_date = forms.DateField(required=True, widget=forms.DateInput(attrs={"type": "date","class": "form-control"}))
	comments = forms.CharField( required=True, widget=forms.Textarea(attrs={"class": "form-control"}))
class LoanAgingLiveUpdateForm(forms.Form):
	overdue_0_30_days = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	overdue_31_60_days = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	overdue_61_90_days = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	overdue_91_days_plus = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	total_outstanding_loans = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	reported_date = forms.DateField(required=True, widget=forms.DateInput(attrs={"type": "date","class": "form-control"}))
	comments = forms.CharField( required=True, widget=forms.Textarea(attrs={"class": "form-control"}))

class AccountsReceivableAgingLiveForm(forms.Form):
	current = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	overdue_30_days = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	overdue_60_days = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	overdue_90_days = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	overdue_90_days_plus = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	reported_date = forms.DateField(required=True, widget=forms.DateInput(attrs={"type": "date","class": "form-control"}))
	total_receivables = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	comments = forms.CharField( required=True, widget=forms.Textarea(attrs={"class": "form-control"}))
class AccountsReceivableAgingTempForm(forms.Form):
	current = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	overdue_30_days = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	overdue_60_days = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	overdue_90_days = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	overdue_90_days_plus = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	reported_date = forms.DateField(required=True, widget=forms.DateInput(attrs={"type": "date","class": "form-control"}))
	total_receivables = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	comments = forms.CharField( required=True, widget=forms.Textarea(attrs={"class": "form-control"}))
class AccountsReceivableAgingTempPAForm(forms.Form):
	current = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	overdue_30_days = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	overdue_60_days = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	overdue_90_days = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	overdue_90_days_plus = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	reported_date = forms.DateField(required=True, widget=forms.DateInput(attrs={"type": "date","class": "form-control"}))
	total_receivables = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	comments = forms.CharField( required=True, widget=forms.Textarea(attrs={"class": "form-control"}))
class AccountsReceivableAgingTempUpdateForm(forms.Form):
	current = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	overdue_30_days = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	overdue_60_days = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	overdue_90_days = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	overdue_90_days_plus = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	reported_date = forms.DateField(required=True, widget=forms.DateInput(attrs={"type": "date","class": "form-control"}))
	total_receivables = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	comments = forms.CharField( required=True, widget=forms.Textarea(attrs={"class": "form-control"}))
class AccountsReceivableAgingLiveUpdateForm(forms.Form):
	current = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	overdue_30_days = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	overdue_60_days = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	overdue_90_days = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	overdue_90_days_plus = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	reported_date = forms.DateField(required=True, widget=forms.DateInput(attrs={"type": "date","class": "form-control"}))
	total_receivables = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	comments = forms.CharField( required=True, widget=forms.Textarea(attrs={"class": "form-control"}))
