from django.urls import path,include
from .views import *

urlpatterns = [
    

    path('dataaccuracy-create/', dataaccuracy_create, name="dataaccuracy_create"),
    path('dataaccuracy-list/', dataaccuracy_list, name="dataaccuracy_list"),
    path('dataaccuracy-pa/<pk>/', dataaccuracy_pa, name="dataaccuracy_pa"),
    path('dataaccuracy-update/<str:code>/', dataaccuracy_update, name="dataaccuracy_update"),
    path('dataaccuracy-view/<str:code>/', dataaccuracy_view, name="dataaccuracy_view"),
    path('dataaccuracy-delete/<pk>/', dataaccuracy_delete, name="dataaccuracy_delete"),
    path('dataaccuracy-authorize-request/<pk>/', dataaccuracy_authorize_request, name="dataaccuracy_authorize_request"),
    path('systemuptime-create/', systemuptime_create, name="systemuptime_create"),
    path('systemuptime-list/', systemuptime_list, name="systemuptime_list"),
    path('systemuptime-pa/<pk>/', systemuptime_pa, name="systemuptime_pa"),
    path('systemuptime-update/<str:code>/', systemuptime_update, name="systemuptime_update"),
    path('systemuptime-view/<str:code>/', systemuptime_view, name="systemuptime_view"),
    path('systemuptime-delete/<pk>/', systemuptime_delete, name="systemuptime_delete"),
    path('systemuptime-authorize-request/<pk>/', systemuptime_authorize_request, name="systemuptime_authorize_request"),
    path('itticketresolution-create/', itticketresolution_create, name="itticketresolution_create"),
    path('itticketresolution-list/', itticketresolution_list, name="itticketresolution_list"),
    path('itticketresolution-pa/<pk>/', itticketresolution_pa, name="itticketresolution_pa"),
    path('itticketresolution-update/<str:code>/', itticketresolution_update, name="itticketresolution_update"),
    path('itticketresolution-view/<str:code>/', itticketresolution_view, name="itticketresolution_view"),
    path('itticketresolution-delete/<pk>/', itticketresolution_delete, name="itticketresolution_delete"),
    path('itticketresolution-authorize-request/<pk>/', itticketresolution_authorize_request, name="itticketresolution_authorize_request"),
    path('accountsreceivableaging_report',accountsreceivableaging_report,name='accountsreceivableaging_report_list'),
    path('assetmanagement_report',assetmanagement_report,name='assetmanagement_report_list'),
    path('balancesheet_report',balancesheet_report,name='balancesheet_report_list'),
    path('branchperformance_report',branchperformance_report,name='branchperformance_report_list'),
    path('cashflowstatement_report',cashflowstatement_report,name='cashflowstatement_report_list'),
    path('clientacquisition_report',clientacquisition_report,name='clientacquisition_report_list'),
    path('clientoutreach_report',clientoutreach_report,name='clientoutreach_report_list'),
    path('compliance_report',compliance_report,name='compliance_report_list'),
    path('customersatisfaction_report',customersatisfaction_report,name='customersatisfaction_report_list'),
    path('dataaccuracy_report',dataaccuracy_report,name='dataaccuracy_report_list'),
    path('feedbackandcomplaints_report',feedbackandcomplaints_report,name='feedbackandcomplaints_report_list'),
    path('fraudmonitoring_report',fraudmonitoring_report,name='fraudmonitoring_report_list'),
    path('incomestatement_report',incomestatement_report,name='incomestatement_report_list'),
    path('itticketresolution_report',itticketresolution_report,name='itticketresolution_report_list'),
    path('leavemanagement_report',leavemanagement_report,name='leavemanagement_report_list'),
    path('loanaging_report',loanaging_report,name='loanaging_report_list'),
    path('loandisbursement_report',loandisbursement_report,name='loandisbursement_report_list'),
    path('loanlossprovision_report',loanlossprovision_report,name='loanlossprovision_report_list'),
    path('logisticsandfleetmanagement_report',logisticsandfleetmanagement_report,name='logisticsandfleetmanagement_report_list'),
    path('officeexpense_report',officeexpense_report,name='officeexpense_report_list'),
    path('portfolioquality_report',portfolioquality_report,name='portfolioquality_report_list'),
    path('riskassessment_report',riskassessment_report,name='riskassessment_report_list'),
    path('staffproductivity_report',staffproductivity_report,name='staffproductivity_report_list'),
    path('staffturnover_report',staffturnover_report,name='staffturnover_report_list'),
    path('systemuptime_report',systemuptime_report,name='systemuptime_report_list'),
    path('trainingdevelopment_report',trainingdevelopment_report,name='trainingdevelopment_report_list')
]