# Generated by Django 5.0 on 2024-11-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MS_ServicePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ms_id', models.CharField(max_length=50)),
                ('serviceplan_id', models.CharField(blank=True, max_length=50, null=True)),
                ('channel_id', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
    ]
