from django import forms
from .models import *
from django.forms import DateInput, DateTimeInput, TimeInput, CheckboxInput, Textarea, TextInput


class CustomerSatisfactionLiveForm(forms.Form):
	surveys_conducted = forms.IntegerField(required=True,widget=forms.NumberInput(attrs={"class": "form-control"}))
	satisfaction_score = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	top_complaints = forms.CharField( required=True, widget=forms.Textarea(attrs={"class": "form-control"}))
	net_promoter_score = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	repeat_customer_percentage = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	reported_date = forms.DateField(required=True, widget=forms.DateInput(attrs={"type": "date","class": "form-control"}))
	survey_response_rate = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	comments = forms.CharField( required=True, widget=forms.Textarea(attrs={"class": "form-control"}))
class CustomerSatisfactionTempForm(forms.Form):
	surveys_conducted = forms.IntegerField(required=True,widget=forms.NumberInput(attrs={"class": "form-control"}))
	satisfaction_score = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	top_complaints = forms.CharField( required=True, widget=forms.Textarea(attrs={"class": "form-control"}))
	net_promoter_score = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	repeat_customer_percentage = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	reported_date = forms.DateField(required=True, widget=forms.DateInput(attrs={"type": "date","class": "form-control"}))
	survey_response_rate = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	comments = forms.CharField( required=True, widget=forms.Textarea(attrs={"class": "form-control"}))
class CustomerSatisfactionTempPAForm(forms.Form):
	surveys_conducted = forms.IntegerField(required=True,widget=forms.NumberInput(attrs={"class": "form-control"}))
	satisfaction_score = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	top_complaints = forms.CharField( required=True, widget=forms.Textarea(attrs={"class": "form-control"}))
	net_promoter_score = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	repeat_customer_percentage = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	reported_date = forms.DateField(required=True, widget=forms.DateInput(attrs={"type": "date","class": "form-control"}))
	survey_response_rate = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	comments = forms.CharField( required=True, widget=forms.Textarea(attrs={"class": "form-control"}))
class CustomerSatisfactionTempUpdateForm(forms.Form):
	surveys_conducted = forms.IntegerField(required=True,widget=forms.NumberInput(attrs={"class": "form-control"}))
	satisfaction_score = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	top_complaints = forms.CharField( required=True, widget=forms.Textarea(attrs={"class": "form-control"}))
	net_promoter_score = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	repeat_customer_percentage = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	reported_date = forms.DateField(required=True, widget=forms.DateInput(attrs={"type": "date","class": "form-control"}))
	survey_response_rate = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	comments = forms.CharField( required=True, widget=forms.Textarea(attrs={"class": "form-control"}))
class CustomerSatisfactionLiveUpdateForm(forms.Form):
	surveys_conducted = forms.IntegerField(required=True,widget=forms.NumberInput(attrs={"class": "form-control"}))
	satisfaction_score = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	top_complaints = forms.CharField( required=True, widget=forms.Textarea(attrs={"class": "form-control"}))
	net_promoter_score = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	repeat_customer_percentage = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	reported_date = forms.DateField(required=True, widget=forms.DateInput(attrs={"type": "date","class": "form-control"}))
	survey_response_rate = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	comments = forms.CharField( required=True, widget=forms.Textarea(attrs={"class": "form-control"}))

class ClientAcquisitionLiveForm(forms.Form):
	new_clients = forms.IntegerField(required=True,widget=forms.NumberInput(attrs={"class": "form-control"}))
	acquisition_cost_per_client = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	total_acquisition_cost = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	average_conversion_rate = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	reported_date = forms.DateField(required=True, widget=forms.DateInput(attrs={"type": "date","class": "form-control"}))
	referral_percentage = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	comments = forms.CharField( required=True, widget=forms.Textarea(attrs={"class": "form-control"}))
class ClientAcquisitionTempForm(forms.Form):
	new_clients = forms.IntegerField(required=True,widget=forms.NumberInput(attrs={"class": "form-control"}))
	acquisition_cost_per_client = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	total_acquisition_cost = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	average_conversion_rate = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	reported_date = forms.DateField(required=True, widget=forms.DateInput(attrs={"type": "date","class": "form-control"}))
	referral_percentage = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	comments = forms.CharField( required=True, widget=forms.Textarea(attrs={"class": "form-control"}))
class ClientAcquisitionTempPAForm(forms.Form):
	new_clients = forms.IntegerField(required=True,widget=forms.NumberInput(attrs={"class": "form-control"}))
	acquisition_cost_per_client = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	total_acquisition_cost = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	average_conversion_rate = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	reported_date = forms.DateField(required=True, widget=forms.DateInput(attrs={"type": "date","class": "form-control"}))
	referral_percentage = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	comments = forms.CharField( required=True, widget=forms.Textarea(attrs={"class": "form-control"}))
class ClientAcquisitionTempUpdateForm(forms.Form):
	new_clients = forms.IntegerField(required=True,widget=forms.NumberInput(attrs={"class": "form-control"}))
	acquisition_cost_per_client = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	total_acquisition_cost = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	average_conversion_rate = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	reported_date = forms.DateField(required=True, widget=forms.DateInput(attrs={"type": "date","class": "form-control"}))
	referral_percentage = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	comments = forms.CharField( required=True, widget=forms.Textarea(attrs={"class": "form-control"}))
class ClientAcquisitionLiveUpdateForm(forms.Form):
	new_clients = forms.IntegerField(required=True,widget=forms.NumberInput(attrs={"class": "form-control"}))
	acquisition_cost_per_client = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	total_acquisition_cost = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	average_conversion_rate = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	reported_date = forms.DateField(required=True, widget=forms.DateInput(attrs={"type": "date","class": "form-control"}))
	referral_percentage = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	comments = forms.CharField( required=True, widget=forms.Textarea(attrs={"class": "form-control"}))

class FeedbackAndComplaintsLiveForm(forms.Form):
	total_complaints_logged = forms.IntegerField(required=True,widget=forms.NumberInput(attrs={"class": "form-control"}))
	resolved_complaints = forms.IntegerField(required=True,widget=forms.NumberInput(attrs={"class": "form-control"}))
	resolution_rate = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	feedback_received = forms.IntegerField(required=True,widget=forms.NumberInput(attrs={"class": "form-control"}))
	positive_feedback_percentage = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	reported_date = forms.DateField(required=True, widget=forms.DateInput(attrs={"type": "date","class": "form-control"}))
	average_resolution_time_hours = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	unresolved_complaints = forms.IntegerField(required=True,widget=forms.NumberInput(attrs={"class": "form-control"}))
	escalation_rate = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	comments = forms.CharField( required=True, widget=forms.Textarea(attrs={"class": "form-control"}))
class FeedbackAndComplaintsTempForm(forms.Form):
	total_complaints_logged = forms.IntegerField(required=True,widget=forms.NumberInput(attrs={"class": "form-control"}))
	resolved_complaints = forms.IntegerField(required=True,widget=forms.NumberInput(attrs={"class": "form-control"}))
	resolution_rate = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	feedback_received = forms.IntegerField(required=True,widget=forms.NumberInput(attrs={"class": "form-control"}))
	positive_feedback_percentage = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	reported_date = forms.DateField(required=True, widget=forms.DateInput(attrs={"type": "date","class": "form-control"}))
	average_resolution_time_hours = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	unresolved_complaints = forms.IntegerField(required=True,widget=forms.NumberInput(attrs={"class": "form-control"}))
	escalation_rate = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	comments = forms.CharField( required=True, widget=forms.Textarea(attrs={"class": "form-control"}))
class FeedbackAndComplaintsTempPAForm(forms.Form):
	total_complaints_logged = forms.IntegerField(required=True,widget=forms.NumberInput(attrs={"class": "form-control"}))
	resolved_complaints = forms.IntegerField(required=True,widget=forms.NumberInput(attrs={"class": "form-control"}))
	resolution_rate = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	feedback_received = forms.IntegerField(required=True,widget=forms.NumberInput(attrs={"class": "form-control"}))
	positive_feedback_percentage = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	reported_date = forms.DateField(required=True, widget=forms.DateInput(attrs={"type": "date","class": "form-control"}))
	average_resolution_time_hours = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	unresolved_complaints = forms.IntegerField(required=True,widget=forms.NumberInput(attrs={"class": "form-control"}))
	escalation_rate = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	comments = forms.CharField( required=True, widget=forms.Textarea(attrs={"class": "form-control"}))
class FeedbackAndComplaintsTempUpdateForm(forms.Form):
	total_complaints_logged = forms.IntegerField(required=True,widget=forms.NumberInput(attrs={"class": "form-control"}))
	resolved_complaints = forms.IntegerField(required=True,widget=forms.NumberInput(attrs={"class": "form-control"}))
	resolution_rate = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	feedback_received = forms.IntegerField(required=True,widget=forms.NumberInput(attrs={"class": "form-control"}))
	positive_feedback_percentage = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	reported_date = forms.DateField(required=True, widget=forms.DateInput(attrs={"type": "date","class": "form-control"}))
	average_resolution_time_hours = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	unresolved_complaints = forms.IntegerField(required=True,widget=forms.NumberInput(attrs={"class": "form-control"}))
	escalation_rate = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	comments = forms.CharField( required=True, widget=forms.Textarea(attrs={"class": "form-control"}))
class FeedbackAndComplaintsLiveUpdateForm(forms.Form):
	total_complaints_logged = forms.IntegerField(required=True,widget=forms.NumberInput(attrs={"class": "form-control"}))
	resolved_complaints = forms.IntegerField(required=True,widget=forms.NumberInput(attrs={"class": "form-control"}))
	resolution_rate = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	feedback_received = forms.IntegerField(required=True,widget=forms.NumberInput(attrs={"class": "form-control"}))
	positive_feedback_percentage = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	reported_date = forms.DateField(required=True, widget=forms.DateInput(attrs={"type": "date","class": "form-control"}))
	average_resolution_time_hours = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	unresolved_complaints = forms.IntegerField(required=True,widget=forms.NumberInput(attrs={"class": "form-control"}))
	escalation_rate = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	comments = forms.CharField( required=True, widget=forms.Textarea(attrs={"class": "form-control"}))
