from django import forms
from .models import *
from django.forms import DateInput, DateTimeInput, TimeInput, CheckboxInput, Textarea, TextInput


class OfficeExpenseLiveForm(forms.Form):
	total_office_expenses = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	top_expenses = forms.CharField( required=True, widget=forms.Textarea(attrs={"class": "form-control"}))
	utilities_expenses = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	rent_expenses = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	office_supplies_expenses = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	reported_date = forms.DateField(required=True, widget=forms.DateInput(attrs={"type": "date","class": "form-control"}))
	employee_welfare_expenses = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	maintenance_expenses = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	comments = forms.CharField( required=True, widget=forms.Textarea(attrs={"class": "form-control"}))
class OfficeExpenseTempForm(forms.Form):
	total_office_expenses = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	top_expenses = forms.CharField( required=True, widget=forms.Textarea(attrs={"class": "form-control"}))
	utilities_expenses = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	rent_expenses = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	office_supplies_expenses = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	reported_date = forms.DateField(required=True, widget=forms.DateInput(attrs={"type": "date","class": "form-control"}))
	employee_welfare_expenses = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	maintenance_expenses = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	comments = forms.CharField( required=True, widget=forms.Textarea(attrs={"class": "form-control"}))
class OfficeExpenseTempPAForm(forms.Form):
	total_office_expenses = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	top_expenses = forms.CharField( required=True, widget=forms.Textarea(attrs={"class": "form-control"}))
	utilities_expenses = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	rent_expenses = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	office_supplies_expenses = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	reported_date = forms.DateField(required=True, widget=forms.DateInput(attrs={"type": "date","class": "form-control"}))
	employee_welfare_expenses = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	maintenance_expenses = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	comments = forms.CharField( required=True, widget=forms.Textarea(attrs={"class": "form-control"}))
class OfficeExpenseTempUpdateForm(forms.Form):
	total_office_expenses = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	top_expenses = forms.CharField( required=True, widget=forms.Textarea(attrs={"class": "form-control"}))
	utilities_expenses = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	rent_expenses = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	office_supplies_expenses = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	reported_date = forms.DateField(required=True, widget=forms.DateInput(attrs={"type": "date","class": "form-control"}))
	employee_welfare_expenses = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	maintenance_expenses = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	comments = forms.CharField( required=True, widget=forms.Textarea(attrs={"class": "form-control"}))
class OfficeExpenseLiveUpdateForm(forms.Form):
	total_office_expenses = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	top_expenses = forms.CharField( required=True, widget=forms.Textarea(attrs={"class": "form-control"}))
	utilities_expenses = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	rent_expenses = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	office_supplies_expenses = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	reported_date = forms.DateField(required=True, widget=forms.DateInput(attrs={"type": "date","class": "form-control"}))
	employee_welfare_expenses = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	maintenance_expenses = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	comments = forms.CharField( required=True, widget=forms.Textarea(attrs={"class": "form-control"}))

class AssetManagementLiveForm(forms.Form):
	total_fixed_assets = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	depreciation = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	maintenance_costs = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	asset_utilization_rate = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	repairs_and_upgrades_cost = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	reported_date = forms.DateField(required=True, widget=forms.DateInput(attrs={"type": "date","class": "form-control"}))
	new_assets_acquired = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	comments = forms.CharField( required=True, widget=forms.Textarea(attrs={"class": "form-control"}))
class AssetManagementTempForm(forms.Form):
	total_fixed_assets = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	depreciation = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	maintenance_costs = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	asset_utilization_rate = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	repairs_and_upgrades_cost = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	reported_date = forms.DateField(required=True, widget=forms.DateInput(attrs={"type": "date","class": "form-control"}))
	new_assets_acquired = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	comments = forms.CharField( required=True, widget=forms.Textarea(attrs={"class": "form-control"}))
class AssetManagementTempPAForm(forms.Form):
	total_fixed_assets = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	depreciation = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	maintenance_costs = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	asset_utilization_rate = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	repairs_and_upgrades_cost = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	reported_date = forms.DateField(required=True, widget=forms.DateInput(attrs={"type": "date","class": "form-control"}))
	new_assets_acquired = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	comments = forms.CharField( required=True, widget=forms.Textarea(attrs={"class": "form-control"}))
class AssetManagementTempUpdateForm(forms.Form):
	total_fixed_assets = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	depreciation = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	maintenance_costs = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	asset_utilization_rate = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	repairs_and_upgrades_cost = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	reported_date = forms.DateField(required=True, widget=forms.DateInput(attrs={"type": "date","class": "form-control"}))
	new_assets_acquired = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	comments = forms.CharField( required=True, widget=forms.Textarea(attrs={"class": "form-control"}))
class AssetManagementLiveUpdateForm(forms.Form):
	total_fixed_assets = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	depreciation = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	maintenance_costs = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	asset_utilization_rate = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	repairs_and_upgrades_cost = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	reported_date = forms.DateField(required=True, widget=forms.DateInput(attrs={"type": "date","class": "form-control"}))
	new_assets_acquired = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	comments = forms.CharField( required=True, widget=forms.Textarea(attrs={"class": "form-control"}))

class LogisticsAndFleetManagementLiveForm(forms.Form):
	total_vehicles = forms.IntegerField(required=True,widget=forms.NumberInput(attrs={"class": "form-control"}))
	vehicles_in_use = forms.IntegerField(required=True,widget=forms.NumberInput(attrs={"class": "form-control"}))
	fuel_costs = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	maintenance_costs = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	vehicle_insurance_expenses = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	reported_date = forms.DateField(required=True, widget=forms.DateInput(attrs={"type": "date","class": "form-control"}))
	vehicle_replacement_value = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	fleet_utilization_rate = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	fleet_safety_compliance_rate = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	vehicle_acquisition_cost = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	comments = forms.CharField( required=True, widget=forms.Textarea(attrs={"class": "form-control"}))
class LogisticsAndFleetManagementTempForm(forms.Form):
	total_vehicles = forms.IntegerField(required=True,widget=forms.NumberInput(attrs={"class": "form-control"}))
	vehicles_in_use = forms.IntegerField(required=True,widget=forms.NumberInput(attrs={"class": "form-control"}))
	fuel_costs = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	maintenance_costs = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	vehicle_insurance_expenses = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	reported_date = forms.DateField(required=True, widget=forms.DateInput(attrs={"type": "date","class": "form-control"}))
	vehicle_replacement_value = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	fleet_utilization_rate = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	fleet_safety_compliance_rate = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	vehicle_acquisition_cost = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	comments = forms.CharField( required=True, widget=forms.Textarea(attrs={"class": "form-control"}))
class LogisticsAndFleetManagementTempPAForm(forms.Form):
	total_vehicles = forms.IntegerField(required=True,widget=forms.NumberInput(attrs={"class": "form-control"}))
	vehicles_in_use = forms.IntegerField(required=True,widget=forms.NumberInput(attrs={"class": "form-control"}))
	fuel_costs = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	maintenance_costs = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	vehicle_insurance_expenses = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	reported_date = forms.DateField(required=True, widget=forms.DateInput(attrs={"type": "date","class": "form-control"}))
	vehicle_replacement_value = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	fleet_utilization_rate = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	fleet_safety_compliance_rate = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	vehicle_acquisition_cost = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	comments = forms.CharField( required=True, widget=forms.Textarea(attrs={"class": "form-control"}))
class LogisticsAndFleetManagementTempUpdateForm(forms.Form):
	total_vehicles = forms.IntegerField(required=True,widget=forms.NumberInput(attrs={"class": "form-control"}))
	vehicles_in_use = forms.IntegerField(required=True,widget=forms.NumberInput(attrs={"class": "form-control"}))
	fuel_costs = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	maintenance_costs = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	vehicle_insurance_expenses = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	reported_date = forms.DateField(required=True, widget=forms.DateInput(attrs={"type": "date","class": "form-control"}))
	vehicle_replacement_value = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	fleet_utilization_rate = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	fleet_safety_compliance_rate = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	vehicle_acquisition_cost = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	comments = forms.CharField( required=True, widget=forms.Textarea(attrs={"class": "form-control"}))
class LogisticsAndFleetManagementLiveUpdateForm(forms.Form):
	total_vehicles = forms.IntegerField(required=True,widget=forms.NumberInput(attrs={"class": "form-control"}))
	vehicles_in_use = forms.IntegerField(required=True,widget=forms.NumberInput(attrs={"class": "form-control"}))
	fuel_costs = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	maintenance_costs = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	vehicle_insurance_expenses = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	reported_date = forms.DateField(required=True, widget=forms.DateInput(attrs={"type": "date","class": "form-control"}))
	vehicle_replacement_value = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	fleet_utilization_rate = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	fleet_safety_compliance_rate = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	vehicle_acquisition_cost = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	comments = forms.CharField( required=True, widget=forms.Textarea(attrs={"class": "form-control"}))
