from django import forms
from .models import *
from django.forms import DateInput, DateTimeInput, TimeInput, CheckboxInput, Textarea, TextInput


class LeaveManagementLiveForm(forms.Form):
	pending_leave_requests = forms.IntegerField(required=True,widget=forms.NumberInput(attrs={"class": "form-control"}))
	total_leave_days_taken = forms.IntegerField(required=True,widget=forms.NumberInput(attrs={"class": "form-control"}))
	average_leave_days_per_staff = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	highest_leave_days = forms.IntegerField(required=False,widget=forms.NumberInput(attrs={"class": "form-control"}))
	lowest_leave_days = forms.IntegerField(required=False,widget=forms.NumberInput(attrs={"class": "form-control"}))
	reported_date = forms.DateField(required=True, widget=forms.DateInput(attrs={"type": "date","class": "form-control"}))
	leave_trends = forms.CharField( required=True, widget=forms.Textarea(attrs={"class": "form-control"}))
	leave_policy_notes = forms.CharField( required=True, widget=forms.Textarea(attrs={"class": "form-control"}))
class LeaveManagementTempForm(forms.Form):
	pending_leave_requests = forms.IntegerField(required=True,widget=forms.NumberInput(attrs={"class": "form-control"}))
	total_leave_days_taken = forms.IntegerField(required=True,widget=forms.NumberInput(attrs={"class": "form-control"}))
	average_leave_days_per_staff = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	highest_leave_days = forms.IntegerField(required=False,widget=forms.NumberInput(attrs={"class": "form-control"}))
	lowest_leave_days = forms.IntegerField(required=False,widget=forms.NumberInput(attrs={"class": "form-control"}))
	reported_date = forms.DateField(required=True, widget=forms.DateInput(attrs={"type": "date","class": "form-control"}))
	leave_trends = forms.CharField( required=True, widget=forms.Textarea(attrs={"class": "form-control"}))
	leave_policy_notes = forms.CharField( required=True, widget=forms.Textarea(attrs={"class": "form-control"}))
class LeaveManagementTempPAForm(forms.Form):
	pending_leave_requests = forms.IntegerField(required=True,widget=forms.NumberInput(attrs={"class": "form-control"}))
	total_leave_days_taken = forms.IntegerField(required=True,widget=forms.NumberInput(attrs={"class": "form-control"}))
	average_leave_days_per_staff = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	highest_leave_days = forms.IntegerField(required=False,widget=forms.NumberInput(attrs={"class": "form-control"}))
	lowest_leave_days = forms.IntegerField(required=False,widget=forms.NumberInput(attrs={"class": "form-control"}))
	reported_date = forms.DateField(required=True, widget=forms.DateInput(attrs={"type": "date","class": "form-control"}))
	leave_trends = forms.CharField( required=True, widget=forms.Textarea(attrs={"class": "form-control"}))
	leave_policy_notes = forms.CharField( required=True, widget=forms.Textarea(attrs={"class": "form-control"}))
class LeaveManagementTempUpdateForm(forms.Form):
	pending_leave_requests = forms.IntegerField(required=True,widget=forms.NumberInput(attrs={"class": "form-control"}))
	total_leave_days_taken = forms.IntegerField(required=True,widget=forms.NumberInput(attrs={"class": "form-control"}))
	average_leave_days_per_staff = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	highest_leave_days = forms.IntegerField(required=False,widget=forms.NumberInput(attrs={"class": "form-control"}))
	lowest_leave_days = forms.IntegerField(required=False,widget=forms.NumberInput(attrs={"class": "form-control"}))
	reported_date = forms.DateField(required=True, widget=forms.DateInput(attrs={"type": "date","class": "form-control"}))
	leave_trends = forms.CharField( required=True, widget=forms.Textarea(attrs={"class": "form-control"}))
	leave_policy_notes = forms.CharField( required=True, widget=forms.Textarea(attrs={"class": "form-control"}))
class LeaveManagementLiveUpdateForm(forms.Form):
	pending_leave_requests = forms.IntegerField(required=True,widget=forms.NumberInput(attrs={"class": "form-control"}))
	total_leave_days_taken = forms.IntegerField(required=True,widget=forms.NumberInput(attrs={"class": "form-control"}))
	average_leave_days_per_staff = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	highest_leave_days = forms.IntegerField(required=False,widget=forms.NumberInput(attrs={"class": "form-control"}))
	lowest_leave_days = forms.IntegerField(required=False,widget=forms.NumberInput(attrs={"class": "form-control"}))
	reported_date = forms.DateField(required=True, widget=forms.DateInput(attrs={"type": "date","class": "form-control"}))
	leave_trends = forms.CharField( required=True, widget=forms.Textarea(attrs={"class": "form-control"}))
	leave_policy_notes = forms.CharField( required=True, widget=forms.Textarea(attrs={"class": "form-control"}))

class StaffProductivityLiveForm(forms.Form):
	total_loan_officers = forms.IntegerField(required=True,widget=forms.NumberInput(attrs={"class": "form-control"}))
	loans_per_officer = forms.IntegerField(required=True,widget=forms.NumberInput(attrs={"class": "form-control"}))
	average_portfolio_per_officer = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	total_loans = forms.IntegerField(required=True,widget=forms.NumberInput(attrs={"class": "form-control"}))
	highest_loans_by_officer = forms.IntegerField(required=False,widget=forms.NumberInput(attrs={"class": "form-control"}))
	reported_date = forms.DateField(required=True, widget=forms.DateInput(attrs={"type": "date","class": "form-control"}))
	lowest_loans_by_officer = forms.IntegerField(required=False,widget=forms.NumberInput(attrs={"class": "form-control"}))
	performance_comments = forms.CharField( required=True, widget=forms.Textarea(attrs={"class": "form-control"}))
class StaffProductivityTempForm(forms.Form):
	total_loan_officers = forms.IntegerField(required=True,widget=forms.NumberInput(attrs={"class": "form-control"}))
	loans_per_officer = forms.IntegerField(required=True,widget=forms.NumberInput(attrs={"class": "form-control"}))
	average_portfolio_per_officer = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	total_loans = forms.IntegerField(required=True,widget=forms.NumberInput(attrs={"class": "form-control"}))
	highest_loans_by_officer = forms.IntegerField(required=False,widget=forms.NumberInput(attrs={"class": "form-control"}))
	reported_date = forms.DateField(required=True, widget=forms.DateInput(attrs={"type": "date","class": "form-control"}))
	lowest_loans_by_officer = forms.IntegerField(required=False,widget=forms.NumberInput(attrs={"class": "form-control"}))
	performance_comments = forms.CharField( required=True, widget=forms.Textarea(attrs={"class": "form-control"}))
class StaffProductivityTempPAForm(forms.Form):
	total_loan_officers = forms.IntegerField(required=True,widget=forms.NumberInput(attrs={"class": "form-control"}))
	loans_per_officer = forms.IntegerField(required=True,widget=forms.NumberInput(attrs={"class": "form-control"}))
	average_portfolio_per_officer = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	total_loans = forms.IntegerField(required=True,widget=forms.NumberInput(attrs={"class": "form-control"}))
	highest_loans_by_officer = forms.IntegerField(required=False,widget=forms.NumberInput(attrs={"class": "form-control"}))
	reported_date = forms.DateField(required=True, widget=forms.DateInput(attrs={"type": "date","class": "form-control"}))
	lowest_loans_by_officer = forms.IntegerField(required=False,widget=forms.NumberInput(attrs={"class": "form-control"}))
	performance_comments = forms.CharField( required=True, widget=forms.Textarea(attrs={"class": "form-control"}))
class StaffProductivityTempUpdateForm(forms.Form):
	total_loan_officers = forms.IntegerField(required=True,widget=forms.NumberInput(attrs={"class": "form-control"}))
	loans_per_officer = forms.IntegerField(required=True,widget=forms.NumberInput(attrs={"class": "form-control"}))
	average_portfolio_per_officer = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	total_loans = forms.IntegerField(required=True,widget=forms.NumberInput(attrs={"class": "form-control"}))
	highest_loans_by_officer = forms.IntegerField(required=False,widget=forms.NumberInput(attrs={"class": "form-control"}))
	reported_date = forms.DateField(required=True, widget=forms.DateInput(attrs={"type": "date","class": "form-control"}))
	lowest_loans_by_officer = forms.IntegerField(required=False,widget=forms.NumberInput(attrs={"class": "form-control"}))
	performance_comments = forms.CharField( required=True, widget=forms.Textarea(attrs={"class": "form-control"}))
class StaffProductivityLiveUpdateForm(forms.Form):
	total_loan_officers = forms.IntegerField(required=True,widget=forms.NumberInput(attrs={"class": "form-control"}))
	loans_per_officer = forms.IntegerField(required=True,widget=forms.NumberInput(attrs={"class": "form-control"}))
	average_portfolio_per_officer = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	total_loans = forms.IntegerField(required=True,widget=forms.NumberInput(attrs={"class": "form-control"}))
	highest_loans_by_officer = forms.IntegerField(required=False,widget=forms.NumberInput(attrs={"class": "form-control"}))
	reported_date = forms.DateField(required=True, widget=forms.DateInput(attrs={"type": "date","class": "form-control"}))
	lowest_loans_by_officer = forms.IntegerField(required=False,widget=forms.NumberInput(attrs={"class": "form-control"}))
	performance_comments = forms.CharField( required=True, widget=forms.Textarea(attrs={"class": "form-control"}))

class TrainingDevelopmentLiveForm(forms.Form):
	training_sessions_conducted = forms.IntegerField(required=True,widget=forms.NumberInput(attrs={"class": "form-control"}))
	staff_trained = forms.IntegerField(required=True,widget=forms.NumberInput(attrs={"class": "form-control"}))
	total_training_costs = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	average_training_cost_per_person = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	training_focus_areas = forms.CharField(required=False, widget=forms.Textarea(attrs={"class": "form-control"}))
	reported_date = forms.DateField(required=True, widget=forms.DateInput(attrs={"type": "date","class": "form-control"}))
	training_feedback_summary = forms.CharField(required=False, widget=forms.Textarea(attrs={"class": "form-control"}))
class TrainingDevelopmentTempForm(forms.Form):
	training_sessions_conducted = forms.IntegerField(required=True,widget=forms.NumberInput(attrs={"class": "form-control"}))
	staff_trained = forms.IntegerField(required=True,widget=forms.NumberInput(attrs={"class": "form-control"}))
	total_training_costs = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	average_training_cost_per_person = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	training_focus_areas = forms.CharField(required=False, widget=forms.Textarea(attrs={"class": "form-control"}))
	reported_date = forms.DateField(required=True, widget=forms.DateInput(attrs={"type": "date","class": "form-control"}))
	training_feedback_summary = forms.CharField(required=False, widget=forms.Textarea(attrs={"class": "form-control"}))
class TrainingDevelopmentTempPAForm(forms.Form):
	training_sessions_conducted = forms.IntegerField(required=True,widget=forms.NumberInput(attrs={"class": "form-control"}))
	staff_trained = forms.IntegerField(required=True,widget=forms.NumberInput(attrs={"class": "form-control"}))
	total_training_costs = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	average_training_cost_per_person = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	training_focus_areas = forms.CharField(required=False, widget=forms.Textarea(attrs={"class": "form-control"}))
	reported_date = forms.DateField(required=True, widget=forms.DateInput(attrs={"type": "date","class": "form-control"}))
	training_feedback_summary = forms.CharField(required=False, widget=forms.Textarea(attrs={"class": "form-control"}))
class TrainingDevelopmentTempUpdateForm(forms.Form):
	training_sessions_conducted = forms.IntegerField(required=True,widget=forms.NumberInput(attrs={"class": "form-control"}))
	staff_trained = forms.IntegerField(required=True,widget=forms.NumberInput(attrs={"class": "form-control"}))
	total_training_costs = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	average_training_cost_per_person = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	training_focus_areas = forms.CharField(required=False, widget=forms.Textarea(attrs={"class": "form-control"}))
	reported_date = forms.DateField(required=True, widget=forms.DateInput(attrs={"type": "date","class": "form-control"}))
	training_feedback_summary = forms.CharField(required=False, widget=forms.Textarea(attrs={"class": "form-control"}))
class TrainingDevelopmentLiveUpdateForm(forms.Form):
	training_sessions_conducted = forms.IntegerField(required=True,widget=forms.NumberInput(attrs={"class": "form-control"}))
	staff_trained = forms.IntegerField(required=True,widget=forms.NumberInput(attrs={"class": "form-control"}))
	total_training_costs = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	average_training_cost_per_person = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	training_focus_areas = forms.CharField(required=False, widget=forms.Textarea(attrs={"class": "form-control"}))
	reported_date = forms.DateField(required=True, widget=forms.DateInput(attrs={"type": "date","class": "form-control"}))
	training_feedback_summary = forms.CharField(required=False, widget=forms.Textarea(attrs={"class": "form-control"}))

class StaffTurnoverLiveForm(forms.Form):
	total_departures = forms.IntegerField(required=True,widget=forms.NumberInput(attrs={"class": "form-control"}))
	total_new_hires = forms.IntegerField(required=True,widget=forms.NumberInput(attrs={"class": "form-control"}))
	turnover_rate = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	current_staff_count = forms.IntegerField(required=True,widget=forms.NumberInput(attrs={"class": "form-control"}))
	total_staff_at_start = forms.IntegerField(required=True,widget=forms.NumberInput(attrs={"class": "form-control"}))
	reported_date = forms.DateField(required=True, widget=forms.DateInput(attrs={"type": "date","class": "form-control"}))
	key_departures = forms.CharField( required=True, widget=forms.Textarea(attrs={"class": "form-control"}))
	hiring_notes = forms.CharField( required=True, widget=forms.Textarea(attrs={"class": "form-control"}))
class StaffTurnoverTempForm(forms.Form):
	total_departures = forms.IntegerField(required=True,widget=forms.NumberInput(attrs={"class": "form-control"}))
	total_new_hires = forms.IntegerField(required=True,widget=forms.NumberInput(attrs={"class": "form-control"}))
	turnover_rate = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	current_staff_count = forms.IntegerField(required=True,widget=forms.NumberInput(attrs={"class": "form-control"}))
	total_staff_at_start = forms.IntegerField(required=True,widget=forms.NumberInput(attrs={"class": "form-control"}))
	reported_date = forms.DateField(required=True, widget=forms.DateInput(attrs={"type": "date","class": "form-control"}))
	key_departures = forms.CharField( required=True, widget=forms.Textarea(attrs={"class": "form-control"}))
	hiring_notes = forms.CharField( required=True, widget=forms.Textarea(attrs={"class": "form-control"}))
class StaffTurnoverTempPAForm(forms.Form):
	total_departures = forms.IntegerField(required=True,widget=forms.NumberInput(attrs={"class": "form-control"}))
	total_new_hires = forms.IntegerField(required=True,widget=forms.NumberInput(attrs={"class": "form-control"}))
	turnover_rate = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	current_staff_count = forms.IntegerField(required=True,widget=forms.NumberInput(attrs={"class": "form-control"}))
	total_staff_at_start = forms.IntegerField(required=True,widget=forms.NumberInput(attrs={"class": "form-control"}))
	reported_date = forms.DateField(required=True, widget=forms.DateInput(attrs={"type": "date","class": "form-control"}))
	key_departures = forms.CharField( required=True, widget=forms.Textarea(attrs={"class": "form-control"}))
	hiring_notes = forms.CharField( required=True, widget=forms.Textarea(attrs={"class": "form-control"}))
class StaffTurnoverTempUpdateForm(forms.Form):
	total_departures = forms.IntegerField(required=True,widget=forms.NumberInput(attrs={"class": "form-control"}))
	total_new_hires = forms.IntegerField(required=True,widget=forms.NumberInput(attrs={"class": "form-control"}))
	turnover_rate = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	current_staff_count = forms.IntegerField(required=True,widget=forms.NumberInput(attrs={"class": "form-control"}))
	total_staff_at_start = forms.IntegerField(required=True,widget=forms.NumberInput(attrs={"class": "form-control"}))
	reported_date = forms.DateField(required=True, widget=forms.DateInput(attrs={"type": "date","class": "form-control"}))
	key_departures = forms.CharField( required=True, widget=forms.Textarea(attrs={"class": "form-control"}))
	hiring_notes = forms.CharField( required=True, widget=forms.Textarea(attrs={"class": "form-control"}))
class StaffTurnoverLiveUpdateForm(forms.Form):
	total_departures = forms.IntegerField(required=True,widget=forms.NumberInput(attrs={"class": "form-control"}))
	total_new_hires = forms.IntegerField(required=True,widget=forms.NumberInput(attrs={"class": "form-control"}))
	turnover_rate = forms.FloatField(required=True, widget=forms.NumberInput(attrs={"class": "form-control"}))
	current_staff_count = forms.IntegerField(required=True,widget=forms.NumberInput(attrs={"class": "form-control"}))
	total_staff_at_start = forms.IntegerField(required=True,widget=forms.NumberInput(attrs={"class": "form-control"}))
	reported_date = forms.DateField(required=True, widget=forms.DateInput(attrs={"type": "date","class": "form-control"}))
	key_departures = forms.CharField( required=True, widget=forms.Textarea(attrs={"class": "form-control"}))
	hiring_notes = forms.CharField( required=True, widget=forms.Textarea(attrs={"class": "form-control"}))
